name: koopa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 1.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.ttf
          weight: 900


